In [3]:
import numpy as np

In [4]:
x = np.array([1,2,3,4])

In [5]:
print(x)

[1 2 3 4]


In [6]:
print(type(x))

<class 'numpy.ndarray'>


In [7]:
print(x.shape)

(4,)


In [8]:
y = np.array([[1,2],[3,4]])

In [9]:
print(y)
print(y.shape)

[[1 2]
 [3 4]]
(2, 2)


In [10]:
z = np.array([[1+0.j,2+5.j]])

In [11]:
print(z)
print(z.shape)

[[1.+0.j 2.+5.j]]
(1, 2)


In [12]:
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
print(a.shape)

(2, 3)


In [14]:
b = np.ones((2,3), dtype=int)

In [15]:
print(b)

[[1 1 1]
 [1 1 1]]


In [16]:
d = np.eye(3)

In [17]:
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
e = np.arange(10)

In [20]:
print(e)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
e = np.arange(12, 21)

In [22]:
print(e) 

[12 13 14 15 16 17 18 19 20]


In [23]:
e = np.arange(5, 20, 3)

In [24]:
print(e)

[ 5  8 11 14 17]


In [25]:
f = np.linspace(1, 20, 7)

In [26]:
print(f)

[ 1.          4.16666667  7.33333333 10.5        13.66666667 16.83333333
 20.        ]


In [27]:
g = np.random.random((3,4))

In [28]:
print(g)

[[0.20492314 0.88371418 0.67769888 0.72764592]
 [0.56655004 0.27324796 0.51427086 0.09938957]
 [0.97281579 0.89598381 0.36402294 0.37363274]]


In [29]:
h = np.random.random((3,4))

In [30]:
print(h.reshape(2,2,3))

[[[0.6223214  0.74360169 0.20771422]
  [0.60367415 0.63994088 0.70846837]]

 [[0.59977406 0.96631192 0.77636311]
  [0.86070768 0.23375279 0.43828202]]]


In [31]:
x = np.arange(12)
print(x)
print(x[4])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
4


In [32]:
print(x[4])

4


In [33]:
print(x[-1])

11


In [34]:
x.resize(3,4)

In [35]:
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [36]:
print(x[-1,-1])

11


In [37]:
print(x[2][3])

11


In [38]:
y = np.arange(1,26)

In [39]:
print(y)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


In [40]:
print(y[:3])

[1 2 3]


In [41]:
print(y[10:])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [42]:
print(y[10:15])

[11 12 13 14 15]


In [43]:
print(y[-5:])

[21 22 23 24 25]


In [44]:
print(y[:-3])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]


In [45]:
print(y[3:-3])

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]


In [46]:
print(y[::3])

[ 1  4  7 10 13 16 19 22 25]


In [47]:
print(y.reshape((5,5)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [50]:
y = y.reshape((5,5))
print(y)
print(y[:5,:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [51]:
print(y[2:-1, 1:-1])

[[12 13 14]
 [17 18 19]]


In [52]:
print(y[:, :-1])

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]
 [21 22 23 24]]


In [53]:
print(y[:, -1])

[ 5 10 15 20 25]


In [54]:
print(y[::, ::2])

[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]
 [21 23 25]]


In [55]:
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [56]:
print(y[1::2, 1::2])

[[ 7  9]
 [17 19]]


In [58]:
a = np.arange(1,6)
b = np.arange(6,11)
print(a+b)
print(a-b)
print(b-a)
print(a**2)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[5 5 5 5 5]
[ 1  4  9 16 25]


In [59]:
print(a>3)

[False False False  True  True]


In [60]:
a = np.arange(0,4).reshape((2,2))

In [61]:
b = np.eye(2)

In [62]:
print(a*b)

[[0. 0.]
 [0. 3.]]


In [63]:
print(np.dot(a,b))

[[0. 1.]
 [2. 3.]]


In [64]:
x = np.arange(1,10).reshape(3,3)

In [65]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [66]:
print(x.sum())

45


In [67]:
print(x.sum(axis=1))

[ 6 15 24]


In [68]:
x = np.arange(1,19).reshape(3,3,2)

In [69]:
print(x.sum(axis=1))

[[ 9 12]
 [27 30]
 [45 48]]


In [70]:
x = np.arange(1,10).reshape(3,3)

In [71]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [72]:
print(x.max())

9


In [73]:
print(x.max(axis=0))

[7 8 9]


In [74]:
print(x.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]
